services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Controller\DefaultController:
        tags: ['controller.service_arguments']
        
    App\Controller\VirtualHostsController:
        arguments:
            - '@vs_app.php_brew'
            - '@vs_app.apache_virtual_host_repository'
            - '@vs_app.apache_virtual_host_factory'
            - '@vs_app.apache_host_actions'
        tags: ['controller.service_arguments']
        
    App\Controller\VirtualHostsOptionsController:
        tags: ['controller.service_arguments']
        
    App\Controller\PhpVersionsController:
        arguments:
            - '@vs_app.php_brew'
            - '@vs_app.apache_service'
            - '%phpbrew_variants%'
            - '%phpbrew_variants_default%'
            - '%kernel.project_dir%'
        tags: ['controller.service_arguments']
    
    App\Controller\PhpBrewExtensionsController:
        arguments:
            - '%kernel.project_dir%'
        tags: ['controller.service_arguments']
    
    App\Controller\TomcatController:
        arguments:
            - '@app.tomcat'
        tags: ['controller.service_arguments']
        
    App\Controller\PythonController:
        arguments:
            - '@app.python'
        tags: ['controller.service_arguments']
        
    App\Controller\ProjectsController:
        arguments:
            - '@vs_app.apache_service'
            - '@vs_app.apache_virtual_host_repository'
        tags: ['controller.service_arguments']
        
    App\Controller\ProjectsInstallController:
        tags: ['controller.service_arguments']
        
    App\Controller\ThirdPartyProjectsController:
        arguments:
#            - '@vs_app.apache_service'
#            - '@vs_app.apache_virtual_host_repository'
        tags: ['controller.service_arguments']
