services:
    _defaults:
        autowire: true
        autoconfigure: true
        
    my_projects.project_source:
        class: App\Component\Installer\ProjectSource
       
    my_projects.predefined_project: 
        class: App\Component\Project\PredefinedProject
        arguments:
            - '@my_projects.project_source'
    