services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        
    my_projects.project_source:
        class: App\Component\Installer\ProjectSource
        
    my_projects.github_api:
        class: App\Component\HttpClient\GitHubApi
        
    my_projects.packagist_api:
        class: App\Component\HttpClient\PackagistApi
       
    my_projects.predefined_project: 
        class: App\Component\Project\PredefinedProject
        arguments:
            - '@service_container'
    