parameters:
    tomcat_instances_dir: '/opt/tomcat'
    
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    app.tomcat:
        public: true
        class: App\Component\Command\Tomcat
        arguments: 
            - '@service_container'