framework:
    assets:
      json_manifest_path: '%kernel.project_dir%/public/build/default/manifest.json'

webpack_encore:
    output_path: '%kernel.project_dir%/public/build/default'
    builds:
        defaultConfig: '%kernel.project_dir%/public/build/default'
        VelzonTheme: '%kernel.project_dir%/public/build/velzon-theme'
