framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    
    #
    # Very-Very Usefull to know about this configuration( especially for route methos PUT and DELETE) 
    # https://symfony.com/doc/current/reference/configuration/framework.html#configuration-framework-http_method_override
    http_method_override: true

    handle_all_throwables: true
    php_errors:
        log: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~
        cookie_secure: auto
        cookie_samesite: lax
        
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
