vs_application_instalator:
    resources:
        instalation_info:
            classes:
                model: App\Entity\Application\InstalationInfo

vs_application:
    resources:
        application:
            classes:
                model: App\Entity\Application\Application
        settings:
            classes:
                model: App\Entity\Application\Settings
        taxonomy:
            classes:
                model: App\Entity\Application\Taxonomy
        taxon:
            classes:
                model: App\Entity\Application\Taxon
            translation:
                classes:
                    model: App\Entity\Application\TaxonTranslation
        taxon_image:
            classes:
                model: App\Entity\Application\TaxonImage
        translation:
            classes:
                model: App\Entity\Application\Translation
        logentry:
            classes:
                model: App\Entity\Application\LogEntry
        locale:
            classes:
                model: App\Entity\Application\Locale
        cookie_consent_translation:
            classes:
                model: App\Entity\Application\CookieConsentTranslation
        tags_whitelist_context:
            classes:
                model: App\Entity\Application\TagsWhitelistContext
        tags_whitelist_tag:
            classes:
                model: App\Entity\Application\TagsWhitelistTag
        widget_group:
            classes:
                model: App\Entity\Application\WidgetGroup
        widget:
            classes:
                model: App\Entity\Application\Widget
        widgets_registry:
            classes:
                model: App\Entity\Application\WidgetsRegistry
                
    menu:              
        mainApplicationMenu:
            mywebprojects_tools:
                name: MyWebProjects Tools
                uri: "javascript:;"
                attributes:
                    id: menu-virtual-hosts
                    iconClass: "fas fa-tools"
                childs:
                    php_info:
                        name: Php Info
                        uri: "/info.php"
                        attributes:
                            target: '_blank'
                    phpmyadmin:
                        name: PhpMyAdmin
                        uri: "/phpmyadmin"
                        attributes:
                            target: '_blank'
                    mailcatcher:
                        name: MailCatcher
                        uri: "http://myprojects.lh:1080/"
                        attributes:
                            target: '_blank'
                    portainer:
                        name: 'Docker Portainer'
                        uri: "https://myprojects.lh:9443/"
                        attributes:
                            target: '_blank'
                    elastic_search:
                        name: 'Elastic Search'
                        uri: "https://myprojects.lh:9200/"
                        attributes:
                            target: '_blank'
                            
            external_tools:
                name: External Tools
                uri: "javascript:;"
                attributes:
                    id: menu-external-tools
                    iconClass: "fas fa-tools"
                childs:
                    php_info:
                        name: Test Jenkins Deployment
                        uri: "http://test-jenkins.vankosoft.org"
                        attributes:
                            target: '_blank'
                    gtmetrix:
                        name: Website Performance Testing
                        uri: "https://gtmetrix.com"
                        attributes:
                            target: '_blank'
                    seotester:
                        name: SEO Tester Online
                        uri: "https://www.seotesteronline.com/"
                        attributes:
                            target: '_blank'
                                   
            dashboard:
                name: vs_application.menu.dashboard
                uri: "javascript:;"
                attributes:
                    id: menu-dashboard
                    iconClass: "fas fa-fw fa-tachometer-alt"
                childs:
                    dashboard:
                        name: vs_application.menu.dashboard
                        uri: "/"
                        attributes:
                            target: '_self'
                
            
            projects_menu:
                name: Projects
                uri: "javascript:;"
                attributes:
                    id: menu-projects-main
                    iconClass: "fas fa-project-diagram"
                childs:
                    projects:
                        name: Projects
                        uri: "/projects"
                        attributes:
                            id: menu-projects
                            target: '_self'
                    virtual_hosts:
                        name: Hosts
                        uri: "/hosts"
                        attributes:
                            id: menu-virtual-hosts
                            target: '_self'
            
            php_menu:
                name: Php
                uri: "javascript:;"
                attributes:
                    id: menu-php
                    iconClass: "fab fa-php"
                childs:
                    php_versions:
                        name: Php Versions
                        uri: "/php-versions"
                        attributes:
                            id: menu-php-versions
                            target: '_self'
                    phpbrew_extensions:
                        name: PhpBrew Extensions
                        route: phpbrew_extensions_index
                        attributes:
                            id: menu-phpbrew-extensions
                            target: '_self'
            
            java_menu:
                name: Java
                uri: "javascript:;"
                attributes:
                    id: menu-java
                    iconClass: "fab fa-java"
                childs:
                    tomcat_instances:
                        name: Tomcat Instances
                        uri: "/tomcat/instances"
                        attributes:
                            id: menu-tomcat-instances
                            target: '_self'
            
            python_menu:
                name: Python
                uri: "javascript:;"
                attributes:
                    id: menu-python
                    iconClass: "fab fa-python"
                childs:
                    python_virtual_environments:
                        name: Python Virtual Environments
                        uri: "/python/virtual-environments"
                        attributes:
                            id: menu-python_virtual_environments
                            target: '_self'       
           

        profileMenu:
            profile:
                name: vs_application.menu.my_profile
                route: vs_users_profile_show
                attributes:
                    iconClass: "fas fa-user mr-2"
            
            documentation:
                name: vs_application.menu.documentation
                uri: "javascript:;"
                attributes:
                    iconClass: "fas fa-cog mr-2"
            
            divider_1:
                isDivider: true
            
            logout:
                name: vs_application.menu.logout
                route: vs_application_logout
                attributes:
                    iconClass: "fas fa-power-off mr-2"
                    
        # Developement Menu loaded in 'templates/layout/menu/developement.html.twig'          
        devMenu:
            devTests:
                name: Developement Tests
                uri: "javascript:;"
                attributes:
                    id: devTests
                childs:
                    #taxonomy_test_products:
                    #    name: Test Taxonomy with Product Categorization
                    #    route: app_test_taxonomy
            appBundle:
                name: Symfony Application Bundle
                uri: "javascript:;"
                attributes:
                    id: appBundle
                childs:
                    settings:
                        name: General Settings
                        route: vs_app_settings_edit
                    taxonomy:
                        name: Taxonomy
                        route: vs_application_taxonomy_index
            cmsBundle:
                name: Symfony Cms Bundle
                uri: "javascript:;"
                attributes:
                    id: cmsBundle
                childs:
                    pages:
                        name: Pages
                        route: vs_cms_pages_index
                    categories:
                        name: Categories
                        route: vs_cms_page_categories_index
                
     