projects:
    resource: "../src/Controller/ProjectsController.php"
    prefix:   /
    type:     annotation
    
app_home:
    path: /
    controller: App\Controller\DefaultController::index
    
app_set_lang:
    path: /set_lang/{lang}
    controller: App\Controller\DefaultController::setLanguage
    
app_set_locale:
    path: /set_locale/{locale}
    controller: App\Controller\DefaultController::setLocale
 