imports:
    - { resource: services/vs_application.yaml }
    - { resource: services/menu.yaml }
    - { resource: services/twig_extensions.yaml }
    - { resource: services/commands.yaml }
    - { resource: services/phpbrew.yaml }
    - { resource: services/tomcat.yaml }
    - { resource: services/python.yaml }
    - { resource: services/controller.yaml }
    - { resource: services/installer.yaml }

parameters:
    siteTitle: 'VS My Projects 2'
    mailer_user: 'admin@myprojects.lh'
    lang: 'en'
    locale: 'en_US'
    
    # Gaufrette File Systems
    vs_cms.gaufrette.profile.filesystem: vs_application_profile
    vs_cms.gaufrette.filemanager.filesystem: vs_application_filemanager
    # Shared Media Directories
    vs_cms.filemanager_shared_media_gaufrette.profile: "%kernel.project_dir%/public/shared_media/gaufrette/profile"
    vs_cms.filemanager_shared_media_gaufrette.filemanager: "%kernel.project_dir%/public/shared_media/gaufrette/filemanager"
    vs_cms.filemanager_shared_media_artgris: '%kernel.project_dir%/public/shared_media/artgris'
    
    virtual_hosts_dir: '/etc/httpd/conf.d'

services:        
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    #twig.extension.date:
    #    class: Twig_Extensions_Extension_Date
    #    tags:
    #        - { name: twig.extension }
    
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude:
            - '../src/DataFixtures/'
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Form/'
            - '../src/Tests/'
            - '../src/Kernel.php'
            - '../src/Controller/'
            - '../src/Component/Command/'
            - '../src/Command/'
        autowire: true
  
    ###################################
    # GREAT DEBUGGING
    ###################################
#     my_blue_screen:
#         class: 'Tracy\BlueScreen'
#         properties:
#             info:
#                 - 'environment: %kernel.environment%'
# 
#     vasek_purchart.tracy_blue_screen.tracy.blue_screen: '@my_blue_screen'
    
    ##################################
    # Form Types with Arguments
    ##################################
    App\Form\Type\HostOptions\ProjectHostLampOptionType:
        arguments: ['@vs_app.php_brew']
        tags: [form.type]
          
    #############################################################################  
