imports:
    - { resource: services/vs_application.yaml }
    - { resource: services/menu.yaml }
    - { resource: services/twig_extensions.yaml }
    - { resource: services/commands.yaml }
    - { resource: services/phpbrew.yaml }
    - { resource: services/tomcat.yaml }
    - { resource: services/python.yaml }
    - { resource: services/controller.yaml }
    - { resource: services/installer.yaml }

parameters:
    locale: 'en_US'
    
    applicationIcon: 'build/default/images/superman.svg'
    applicationCompany: 'vs_application.template.vankosoft_application'
    applicationTitle: 'VS My Projects 2'
    hasTopSearch: true
    
    vs_application.version: !php/const App\Kernel::VERSION
    vs_application.public_dir: "%kernel.project_dir%/public/admin-panel"
    vs_application.taxon_repository_throw_exception: false
    vs_application.page_categories.taxonomy_code: 'page-categories'
    
    vs_users.login_route: 'vs_application_login'
    vs_users.login_by: 'username'
    vs_users.form_create_account: false
    vs_users.default_redirect: 'vs_application_dashboard'
    vs_users.crud.display_siblings: false
    
    # The cookie_lifetime would be set to a relatively high value, 
    # and the garbage collection gc_maxlifetime would be set to destroy sessions at whatever the desired idle period is.
    #########################################################################################################################
    vs_users.gc_maxlifetime: 1800   # 30 minutes
    vs_users.cookie.domain: '%env(COOKIE_DOMAIN)%'
    vs_users.cookie.lifetime: 86400 # 24 hours
    
    # Gaufrette File Systems
    vs_cms.gaufrette.profile.filesystem: vs_application_profile
    vs_cms.gaufrette.filemanager.filesystem: vs_application_filemanager
    # Shared Media Directories
    vs_cms.filemanager_shared_media_gaufrette.profile: "%kernel.project_dir%/public/shared_media/gaufrette/profile"
    vs_cms.filemanager_shared_media_gaufrette.filemanager: "%kernel.project_dir%/public/shared_media/gaufrette/filemanager"
    vs_cms.filemanager_shared_media_artgris: '%kernel.project_dir%/public/shared_media/artgris'
    
    virtual_hosts_dir: '/etc/httpd/conf.d'

services:        
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    #twig.extension.date:
    #    class: Twig_Extensions_Extension_Date
    #    tags:
    #        - { name: twig.extension }
    
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude:
            - '../src/DataFixtures/'
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Form/'
            - '../src/Tests/'
            - '../src/Kernel.php'
            - '../src/Controller/'
            - '../src/Component/Command/'
            - '../src/Command/'
        autowire: true
  
    ###################################
    # GREAT DEBUGGING
    ###################################
#     my_blue_screen:
#         class: 'Tracy\BlueScreen'
#         properties:
#             info:
#                 - 'environment: %kernel.environment%'
# 
#     vasek_purchart.tracy_blue_screen.tracy.blue_screen: '@my_blue_screen'
    
    ##################################
    # Form Types with Arguments
    ##################################
    App\Form\Type\HostOptions\ProjectHostLampOptionType:
        arguments: ['@vs_app.php_brew']
        tags: [form.type]
          
    #############################################################################  
